### ISSUE TITLE
Opciones nuevas 

### ISSUE THREAD

**Issue by beniiju** [Alezito2008/Python-Kahoot-Flooder#1]
Dejo unas propuestas:
-Mejor velocidad de la página 
-Más Configuraciones 
-Más grande el texto

**Comment by beniiju** [comment]
Tenes razón,por eso te dejo un Like de oro xD

**Comment by Alezito2008** [comment]
Gracias bro, algo más?

**Comment by beniiju** [comment]
Pasame tu teléfono! Así hablamos..... XD

**Comment by Alezito2008** [comment]
Tu vieja
